### ISSUE TITLE
Unable to get this to work in Windows

### ISSUE THREAD

**Issue by justinds89** [fablabnbg/inkscape-centerline-trace#10]
Hello I am using the latest version of Inkscape and have been trying to find a way to do center line tracing in Inkscape, but I am unable to get this extension to work.

Any help would be appreciated.

**Comment by jnweiger** [comment]
Please check out https://github.com/fablabnbg/inkscape-centerline-trace/issues/5 -- there are instructions for windows near the end. Great help, if you can test and report back there. thanks!

closed duplicate.
