### ISSUE TITLE
Can centerline-trace create more detailed paths?

### ISSUE THREAD

**Issue by unfa** [fablabnbg/inkscape-centerline-trace#12]
Sometimes I'd like to have more points in the created paths, to have sharper corners and more detail.
The current results are great, but often I'd like to have more points created.

**Comment by jnweiger** [comment]
There are some builtin constants in autotrace, that I am not exposing via the interface. Maybe it helps to enlarge your drawing by a factor of 10, then trace, then shrink back to original size?

**Comment by jnweiger** [comment]
If that workaround is what you need, I can easily add a details slider too. Please also show an example where the missing details are apparent.

**Comment by jnweiger** [comment]
@unfa now there are two additional options to tune how detailled to follow the path.
Check out verison 0.8b or later.
![grafik](https://user-images.githubusercontent.com/1108546/45007776-ab48db00-afff-11e8-8e4e-ddb13f2f8118.png)

**Comment by Moini** [comment]
Very cool, jnweiger! I didn't know this was possible. 

Probably at some point, we're going to need a help tab to explain the options (or need some mouseover text for it) :)
