### ISSUE TITLE
Error: No available formula with the name "autotrace" 

### ISSUE THREAD

**Issue by alelordelo** [fablabnbg/inkscape-centerline-trace#13]
Hi there!

Centerline is asking me to install homebrew + autotrace.

Homebrew was installed fine, but autotraceis giving me the error bellow:

Error: No available formula with the name "autotrace" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Any idea on what this could be?

thanks!

**Comment by jnweiger** [comment]
I cannot help much here. I don't own a mac and never used homebrew myself. Google points me to http://macappstore.org/autotrace/ which looks like autotrace is available for mac too.

**Comment by su-v** [comment]
AFAICT the formula to build autotrace was deleted from homebrew a week ago:
* [autotrace: delete](https://github.com/Homebrew/homebrew-core/pull/13897) - Pull Request 13897 · Homebrew/homebrew-core

According to that PR, it's also already gone from Debian unstable. Other distros might follow?

**Comment by deme-rs** [comment]
If you're willing to live with the vulnerabilities, you can compile autotrace from source.

On macOS Sierra, the build script detects libpng, but compilation fails due to a deprecated header. Png output is not required for this extension, so I commented the line that sets HAVE_LIBPNG_STAGE1 to yes (line 8309 in configure).
Then do the usual ./configure, make, make install and the Inkscape extension will work nicely.

**Comment by jnweiger** [comment]
Ouch. So I am apparently riding a dead horse:
http://blogs.gentoo.org/ago/2017/05/20/autotrace-multiple-vulnerabilities-the-autotrace-nightmare/ is really scary.

To my knowledge, autotrace is the only free vectorizer engine that can trace on the centerline between two edges. Any pointers to a different engine that could be helpful here?

**Comment by jnweiger** [comment]
I have created an Autotrace.app for MacOS 
https://github.com/jnweiger/autotrace/releases
Not yet merged back into https://github.com/autotrace/autotrace -- but it should already fix this issue.
