### ISSUE TITLE
not working correctly in Windows7

### ISSUE THREAD

**Issue by trader4300** [fablabnbg/inkscape-centerline-trace#15]
I have spent many hours trying to get this to work unsuccessfully. A friend of mine was able to get it to work just fine on his Linux machine using this same image. When I run it on mine, I just get a bunch of messages and it hangs there. See below the messages. Hopefully, they mean something to you. I really need this feature to work correctly for my work. I thank-you in advance.
Traceback (most recent call last):
  File "centerline-trace.py", line 441, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "centerline-trace.py", line 402, in effect
    path_svg,stroke_width,im_size = self.svg_centerline_trace(filename)
  File "centerline-trace.py", line 292, in svg_centerline_trace
    xml = inkex.etree.fromstring(cand['svg'])
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src\lxml\lxml.etree.c:77697)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:116494)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:115144)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:109543)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:104201)
lxml.etree.XMLSyntaxError: None

![ceneter-cut-flower](https://user-images.githubusercontent.com/13419734/28122934-a5c73232-66ed-11e7-908d-9d7f40686cd3.png)

**Comment by Moini** [comment]
Hi :) I can reproduce this on a test Win10 VM, but have no idea how to solve.

**Comment by Moini** [comment]
Just remembered that someone posted instructions here: https://inkscape.org/en/gallery/item/10567/centerline_NIH0Rhk.pdf . Unfortunately, this doesn't solve the problem here, but at least shortens installation considerably...

**Comment by jnweiger** [comment]
Hey @Moini with your reproducer, can you find which versions of the python libs you have?
I'd suspect that the lxml python package is especially old or escpecially new thus causing issues?

... Glad you are around :-)

**Comment by Moini** [comment]
I can try... Windows is horrible... :-P ... it's 3.6.4 . On my Linux machine, I have 3.5.0.

**Comment by Moini** [comment]
I think pip allows to install a specific version...

**Comment by jnweiger** [comment]
oh, its the first attempt to parse what is returned from autotrace. Maybe autotrace wanted to tell us some error messages..... does the above commit help catching the error messages?

**Comment by Moini** [comment]
Yeah - changing the version doesn't make a difference (even after deleting the pyc files).
Error message:

```
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
autotrace_cmd: autotrace --centerline --input-format=pbm --output-format=svg
ERROR: no proper xml returned: ''
Traceback (most recent call last):
  File "centerline-trace.py", line 447, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "centerline-trace.py", line 409, in effect
    xml = inkex.etree.fromstring(path_svg)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src\lxml\lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:123074)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:117114)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:111367)
lxml.etree.XMLSyntaxError: None
```

**Comment by trader4300** [comment]
I followed up with performing the installation instructions. I put the autotrace executable as well as the rof.py into the correct folder on inkscape. Then ran a fresh copy of inkscape on an image. Centerline Trace essentially hung up and I had to kill the process. I did get the following though, if it means anything to you folks:
Traceback (most recent call last):
  File "centerline-trace.py", line 441, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "centerline-trace.py", line 402, in effect
    path_svg,stroke_width,im_size = self.svg_centerline_trace(filename)
  File "centerline-trace.py", line 292, in svg_centerline_trace
    xml = inkex.etree.fromstring(cand['svg'])
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src\lxml\lxml.etree.c:77697)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:116494)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:115144)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:109543)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:104201)
lxml.etree.XMLSyntaxError: None

**Comment by jnweiger** [comment]
@Moini you got ERROR: no proper xml returned: ''
that means, autotrace is not working at all.
Please try calling autotrace manually with a simple *.pbm file and see if it behaves?
Please try switching to debug=True near line 70 of centerline-trace.py

**Comment by Moini** [comment]
(Windows sucks...) 

Using autotrace (the exe file copied into the extensions directory) works with a pbm (it outputs lots of stuff that looks like some kind of path format). 

Perhaps I somehow need to add it to the path variable... 

Okay, so I copied the exe file into a new directory, i.e. ...\share\extensions\autotrace.
Added that directory to the PATH system variable (thank god there's a search function in the settings which finds it when you enter 'path').
Rebooted, just for good measure, and deleted all other autotrace exes from previous attempts.
Works now.

**Comment by Moini** [comment]
So the only thing that is missing from the instructions in the pdf is that the directory containing autotrace.exe needs to be added to the path system variable.

**Comment by Moini** [comment]
For @trader4300 , this means:

Try to remove all the other autotraces that you have.
Put the exe linked in the pdf (https://github.com/scottvr/autotrace-win64-binaries/raw/master/bin/autotrace.exe) into an empty new directory of your choice.
Add that directory to your path.

**Comment by trader4300** [comment]
Just to be clear:
Originally, from instructions somewhere, I unzipped the autotrace file into a directory. I then added the directory path to the PATH variable. I was then instructed to copy the autotrace,exe file into the inkscape/share/extentions directory. So, just to be clear:
1.  I do not need all the other files that come with the autotrace zip file and I can remove them from the directory?
2. I do not need the autotrace.exe file in the inkscape directory any longer.
3. Remove any other instances of autotrace.exe
4. Be sure my PATH variable has the directory to the autotrace.exe file
John - trader4300

**Comment by Moini** [comment]
1. No. You need to use the autotrace.exe from the repository linked in the pdf file. And that one only. At least, I have not tested this with the other autotrace.exe from the sourceforge page zip file. It might work, but I didn't try and cannot tell you how. Certainly it will work differently.
2. You only need that single exe, which you place into its own folder (and I cannot promise you that it's trustworthy, use any exe files you download from the internet at your own risk).
3. Yes.
4. Yes.

**Comment by trader4300** [comment]
OK, I will fix this up and try it again. You have been very helpful. Thank-you

**Comment by trader4300** [comment]
OK, getting closer but not there yet. I imported a simple leaf image (see attached). I then executed the centerline trace on it. I saw the command window with autotrace.exe in it flash several dozen times around on my screen and then it was finished. The resulting image doesn't look anything like my leaf, plus the lines are way too thick. So, after looking at this, what do you think is going on? Is there a log file anywhere I can send you?
![traced leaf](https://user-images.githubusercontent.com/13419734/28133925-6cebe0e4-670f-11e7-8d30-70d9c14ad7be.png)
![leaf 1](https://user-images.githubusercontent.com/13419734/28133940-79f5fb80-670f-11e7-8a9b-ee0f2badcf67.jpg)

**Comment by trader4300** [comment]
Hey Folks, After tweeking a few of the settings, I got it to work perfectly. I am already halfway thru my project and everything looks great. This centerline trace feature was the key to everything turning out the right way. Thank-you for all the help. Much Appreciated!

**Comment by Moini** [comment]
Cool :) Perhaps we should post this success on the forums, too ;-) (perhaps with a picture of the result?)

**Comment by jnweiger** [comment]
Glad to hear you succeeded. Thank you @Moini for your helping hand! 
I already recognized where the leaf is in the strange result. There is probably too much magic image 'improvement' going on in the background when the settings are not default settings.

**Comment by trader4300** [comment]
You are right. Changed that back to default and everything worked.However, it does come out a bit smoother than the original. Is there any threshold for this that might limit the amount of smoothing it does?


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jürgen Weigert <notifications@github.com> Date: 7/12/17  7:08 PM  (GMT-05:00) To: fablabnbg/inkscape-centerline-trace <inkscape-centerline-trace@noreply.github.com> Cc: trader4300 <obrien52@rochester.rr.com>, State change <state_change@noreply.github.com> Subject: Re: [fablabnbg/inkscape-centerline-trace] not working correctly in
  Windows7 (#15) 
Glad to hear you succeeded. Thank you @Moini for your helping hand!

I already recognized where the leaf is in the strange result. There is probably too much magic image 'improvement' going on in the background when the settings are not default settings.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fablabnbg/inkscape-centerline-trace","title":"fablabnbg/inkscape-centerline-trace","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fablabnbg/inkscape-centerline-trace"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jnweiger in #15: Glad to hear you succeeded. Thank you @Moini for your helping hand! \r\nI already recognized where the leaf is in the strange result. There is probably too much magic image 'improvement' going on in the background when the settings are not default settings. "}],"action":{"name":"View Issue","url":"https://github.com/fablabnbg/inkscape-centerline-trace/issues/15#issuecomment-314923245"}}}

**Comment by trader4300** [comment]
Regarding the above statement about "smoothing", see the 2 images below. The original is before the Centerline Trace. The other is after the Trace. Notice how the edges are smoothed out quite a bit and on the right side, one curve is missing all together. Is there a setting to tweak this or is it just part of the algorithm? Just thought I would squeeze one last bit of blood... (LOL)
![centerline traced center](https://user-images.githubusercontent.com/13419734/28146106-569fe214-6745-11e7-8747-a5437c2a0bad.png)
![center2](https://user-images.githubusercontent.com/13419734/28146113-5ed5b832-6745-11e7-9ae8-6cbd3d5d7046.png)

**Comment by Moini** [comment]
@trader4300 and @jnweiger  : one of you should better request a new github api key, one has leaked in this post: https://github.com/fablabnbg/inkscape-centerline-trace/issues/15#issuecomment-314937962 . 
I suspect it's trader's, but not sure.

**Comment by jdexter27** [comment]
help me pls!

Traceback (most recent call last):
  File "C:/Program Files (x86)/Inkscape/lib/python2.7/site.py", line 64, in <module>
    import traceback
ImportError: Bad magic number in C:\Program Files (x86)\Inkscape\python\Lib/traceback.pyc

**Comment by jnweiger** [comment]
@trader4300 new version of inksape-centerline-trace 0.8b has two extra settings error-threshold and filter-iterations to control how fine we follow the original path. 

Works great with your rose and the ring-thing, but gives me the shivers with the leaf. I see very well what the issue is, but have to scratch my head what to do here.
[rose-leaf-ring.zip](https://github.com/fablabnbg/inkscape-centerline-trace/files/2348548/rose-leaf-ring.zip)
![grafik](https://user-images.githubusercontent.com/1108546/45030771-40be8c00-b04d-11e8-93ad-255bbc8de461.png)

The green ring-thing (17 nodes) was done with filter-iterations=0, the blue one (14 nodes) with error-threshold=1.0, the black one (10 nodes) with defaults.
