### ISSUE TITLE
Python install script errors

### ISSUE THREAD

**Issue by oldergeek** [fablabnbg/inkscape-centerline-trace#16]
New to Python. Long time inkscape user.  Very interested in Centerline functions.  Currently running Inkscape 0.92.1 r15371, on Windows 10.  I'm using Power shell (as Admin) and not command. 

Following instructions provided in centerline_NIH0Rhk%20(4).pdf.  can't get past the first step.  Keep getting syntax error messages from Python when it executes the get-pip.py script.  I have tried the following: 

1. Using # as remark header, I have remarked out the offending lines as the error messages came up.
this just results in the next line showing a syntax message. 
2.  I made sure that the python install option was checked when Inkscape was installed.  
3. Went back and uninstalled all inkscape versions and then tried again.

I am now stumped.  I have only found one real hit on this problem and that was in this thread (https://github.com/fablabnbg/inkscape-centerline-trace/issues/15) none of those suggested solutions seem to be applicable until I can get past the Python instal.

**Comment by jnweiger** [comment]
Fixed. 

We now have proper setup.exe for windows 10 and inkscape 0.92.3. Please try again with
* install the latest setup.exe from https://github.com/jnweiger/autotrace/releases
* install the latest setup.exe from https://github.com/fablabnbg/inkscape-centerline-trace/releases
* restart inkscape, enjoy.
