### ISSUE TITLE
Add linux installation instructions

### ISSUE THREAD

**Issue by prkos** [fablabnbg/inkscape-centerline-trace#20]
Thank you so much for this wonderful extension! We've had some fun with it on the #inkscape-devel IRC earlier today :) 

But if I hadn't had help from that IRC I wouldn't know how to install this extension. It would be enough to add that you need autotrace package from the default repo. For Ubuntu: 

`sudo apt install autotrace` 

And the reminder to avoid subfolders within extensions/ folder is also necessary ;)

**Comment by Moini** [comment]
Hi prkos ;-)

It would also need info that autotrace isn't available for > 16.04, plus info how to else install it... Did you  find out anything about that, @prkos ?

I just saw that @jnweiger and others have already started to work on autotrace (in another repo here). (This is because I'm currently writing an email to invite him to the Kiel Hackfest ;-)  - although he might prefer to only come to Saarbrücken, which is a lot closer for him).

**Comment by Moini** [comment]
@jnweiger Those are awesome news :D Can you point us to the now official repo? (I didn't check out the forks closely, just noticed that there were commits)
I don't know if Marc (the dev who was interested) has an account on github, but we can notify him of it when we know where :) 

Mc has also expressed interest in coming to Kiel, as well as @doctormo , who is currently working on the extensions.

**Comment by Moini** [comment]
(Oh - what about triple choc :chocolate_bar: :chocolate_bar: :chocolate_bar:  soft-baked cookies :cookie: ? Those are my personal favourites.)

**Comment by jnweiger** [comment]
Hottest development branch for autotrace is https://github.com/lemenkov/autotrace/tree/future
Nothing official in terms of releases yet. If anybody needs help here at github, let me know.

**Comment by Moini** [comment]
Thank you, @jnweiger ! I've sent Mc an email about it.

**Comment by jnweiger** [comment]
gitlab vs github .... hmmm, feel free to mention mention me at https://gitlab.com/jnweiger too :-)

**Comment by Moini** [comment]
I would, if Inkscape used it for bug reports... Currently, it's only used for merge request discussions, marketing discussions and Inkscape website bugs. Inkscape program bugs still live on [launchpad](https://bugs.launchpad.net/inkscape) - and that doesn't even have a mention feature... Oh, and we're discussing [where to move the bug tracker](https://gitlab.com/inkscape/infra/services/issues/2) on gitlab.

**Comment by Moini** [comment]
@prkos Can we close this?

**Comment by prkos** [comment]
Wow how fast you move! Awesome! TY :nerd_face: 

@Moini you need to update your hackfest writeup with cookie info. That might be the crucial tipping point for many to decide to come :D

**Comment by jnweiger** [comment]
@prkos please regard that cookie incident as mere anecdotal evidence. It might also have worked with beer, seafood, or Schweinshaxe. In my case at least :-) 

Thanks @Moini great help (in multiple dimensions)!

**Comment by Moini** [comment]
Ha, we can't serve beer - but seafood is quite possible in Kiel (Sprotten, anyone? :fish: They exist in chocolate form, too ;-) :relieved: ).

@jnweiger I think this extension is a really important thing for Inkscape. It's well worth the effort, and I'm just very glad that you're maintaining it, and are teaming up to keep it alive.
