### ISSUE TITLE
SyntaxError: EOL while scanning string literal in centerline-trace.py

### ISSUE THREAD

**Issue by ST0PPELB4RT** [fablabnbg/inkscape-centerline-trace#24]
First of all thanks for developing such useful tool!

While trying to run centerline I got this error-message
I installed the most recent Inkscape (0.92.3) as well as the most recent autotrace (the one you linked) and version 0.7a of centerline
```
File "centerline-trace.py", line 125
    command = autotrace_exe + ' --version"
                                         ^
SyntaxError: EOL while scanning string literal
```

**Comment by Moini** [comment]
Looks like mixed quotes are being used.

You can fix them yourself (just replace the double-quote at the end by a single quote), pull the code from this merge request:
https://github.com/fablabnbg/inkscape-centerline-trace/pull/25
or wait until it's merged.

**Comment by ST0PPELB4RT** [comment]
Thanks! 
Dammit, should have seen it by myself

**Comment by jnweiger** [comment]
Thanks for reporting, @ST0PPELB4RT thanks for the quick fix, @Moini 
merged.

**Comment by jnweiger** [comment]
https://github.com/fablabnbg/inkscape-centerline-trace/releases/tag/v0.7a
released an updated deb package....

**Comment by Moini** [comment]
Thanks for merging, @jnweiger !
