### ISSUE TITLE
cannot vectorize image with gradient background

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/inkscape-centerline-trace#28]
This leaf gives me a headache. All I can do currently is this: 
![grafik](https://user-images.githubusercontent.com/1108546/45031028-00abd900-b04e-11e8-9c2e-b3c453658139.png)
Original image from #15  by @trader4300:

![leaf-issue15](https://user-images.githubusercontent.com/1108546/45031105-3650c200-b04e-11e8-9520-8fe4b0a4b501.jpg)

**Comment by Moini** [comment]
It works with the rectangle option. Maybe it has to do with the background being uneven?

**Comment by jnweiger** [comment]
That is so cool! I added the cliprect for something completely different. And you solve a new problem with that. Love it!

It is definitly being fooled by the coloring of the background.

**Comment by Moini** [comment]
I don't know about the type of preprocessing you're doing - would being able to define a threshold for black/white help with this? Or maybe it could determine that from the image itself? The cream and white are quite different from the grey/black.... Just thinking out loud - I don't know at all how to do this, or if it would help.

**Comment by jnweiger** [comment]
Try this: python-2.7.15 with Pillow 5.1.0
```
from PIL import Image, ImageOps
im = Image.open('leaf-issue15.jpg')
im = im.convert(mode='L', dither=None)
ImageOps.autocontrast(im, cutoff=2).show()
```
![grafik](https://user-images.githubusercontent.com/1108546/45061351-75116700-b0a4-11e8-9108-730f28d444a8.png)

Wow, that looks like Pillow is misbehaving! No wonder poor autotrace has trouble thereafter!

**Comment by jnweiger** [comment]
* Opened https://github.com/python-pillow/Pillow/issues/3331 
* Removing the cutoff in version 0.8c

**Comment by Moini** [comment]
Urghs! So the cutoff is actually the culprit... :/ How weird. Do you mean to add the functionality back in when the linked issue is solved (or check for version numbers?)

**Comment by jnweiger** [comment]
hmm, probably not worth it. cutoff=2 was more a safety idea than a necessity.

**Comment by Moini** [comment]
Okay, thanks!
