### ISSUE TITLE
Python 3 and Inkscape v1 compatibility

### ISSUE THREAD

**Issue by SmileyChris** [fablabnbg/inkscape-centerline-trace#35]
I've just done a quick fixup in my fork to make this work for me. Didn't do the backwards compatible work to keep the previous versions working, so I'm not doing this as a PR - but in case anyone wants it, or to use it as the base for a proper PR, it's here https://github.com/SmileyChris/inkscape-centerline-trace

**Comment by Moini** [comment]
The functionality is integrated in Inkscape 1.0, in case you didn't know. It's still needed as an extension for Inkscape 0.92.5.

**Comment by SmileyChris** [comment]
No I didn't know - that's hilarious 😆 
Thanks for the head's up! I don't know how I overlooked that dropdown - https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#centerline
