### ISSUE TITLE
correct installation / menu options

### ISSUE THREAD

**Issue by thijsdeschildre** [fablabnbg/inkscape-centerline-trace#36]
I installed this plugin as described, and I'm not getting very good results. 
Under Trace "Bitmap > Single Scan" I see"Autotrace" and "Centerline tracing (autotrace)".  The menu options look different from the screenshots.  I'm on Windows 10, inkscape 1,0 4035a4fb49, 2020-05-01.
I tried to apply the plugin on an image from the main page, and it doesn't work . Fiddling around with all the different parameters available, it doesn't make much of a difference. 
Attaching a screenshot. 

Did I do something wrong with installation? Wrong options clicked in the GUI? Did the plugin break with some Inkscape update?
![centerline-test](https://user-images.githubusercontent.com/2645276/91737085-e4949100-ebae-11ea-9498-be682baada1c.png)

**Comment by thijsdeschildre** [comment]
OK, damn, the plugin is still under Extensions > Images

**Comment by Moini** [comment]
If you're using Inkscape 1.0, you don't need the extension. You can find centerline tracing in the Path > Trace bitmap dialog. I think the extension will also cease to work soon, or doesn't work anymore with current Inkscape versions.

If the Trace Bitmap dialog doesn't work, please report a bug at https://inkscape.org/report . Please also include any files that are relevant to the problem.
