### ISSUE TITLE
Extension creates file in my extensions directory

### ISSUE THREAD

**Issue by Moini** [fablabnbg/inkscape-centerline-trace#4]
The extension creates a new file (`/home/<username>/.config/inkscape/extensions/CON:`) in my extensions directory on Linux Mint 17.3 (based on Ubuntu 14.04) when I run it.

This seems to be due to the line 
`self.tty = open("CON:", 'w')   # windows. Does this work???`

Can this be prevented? I don't think the file is needed on Linux, and I don't want extensions to meddle with the contents of my extensions directory.

**Comment by jnweiger** [comment]
Oh. That is unintended. Sorry.

**Comment by Moini** [comment]
Thank you!

**Comment by jnweiger** [comment]
Please check out https://github.com/fablabnbg/inkscape-centerline-trace/releases/tag/v0.5
