### ISSUE TITLE
ImportError: The _imaging C module is not installed

### ISSUE THREAD

**Issue by Hansie17** [fablabnbg/inkscape-centerline-trace#5]
I'm getting the below error on Inkscape 0.91 (Windows 10) and wondered if you might be able to advise how I can fix. I've tried various fixes for this error, but cannot seem to resolve. I do understand that this is not an issue with your script but likely a configuration problem with my Inkscape install.

Thanks and regards,
Hans

"Traceback (most recent call last):
  File "centerline-trace.py", line 392, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "centerline-trace.py", line 359, in effect
    path_svg,stroke_width,im_size = self.svg_centerline_trace(filename)
  File "centerline-trace.py", line 154, in svg_centerline_trace
    im = im.convert(mode='L', dither=None)
  File "C:\Program Files\Inkscape\python\lib\site-packages\PIL\Image.py", line 653, in convert
    self.load()
  File "C:\Program Files\Inkscape\python\lib\site-packages\PIL\ImageFile.py", line 155, in load
    self.load_prepare()
  File "C:\Program Files\Inkscape\python\lib\site-packages\PIL\PngImagePlugin.py", line 339, in load_prepare
    ImageFile.ImageFile.load_prepare(self)
  File "C:\Program Files\Inkscape\python\lib\site-packages\PIL\ImageFile.py", line 223, in load_prepare
    self.im = Image.core.new(self.mode, self.size)
  File "C:\Program Files\Inkscape\python\lib\site-packages\PIL\Image.py", line 36, in **getattr**
    raise ImportError("The _imaging C module is not installed")
ImportError: The _imaging C module is not installed"

**Comment by contraburn** [comment]
same problem, and it is not solved on 64 bit windows with reinstalled 64 bit inkscape by: uninstall 32 bit python; clean install 64 bit 3.5.2 python; pip uninstall pil; pip uninstall pillow; pip install pillow

**Comment by contraburn** [comment]
32 bit versions also have this problem.  I found an extension XIA which according to the discussion at http://www.inkscapeforum.com/viewtopic.php?t=18416
" installer we made available will override the python version of inkscape to add this graphical lib. The installer will install xia in C:/Program Files/Inkscape/extensions/     I know it has already been discussed here to embed graphical lib in the inkscape python version and, if I remember, the core team refused to do such a thing. "
when I use their installer, the "imaging C module" problem seems to be gone, but I can't be sure because the extension never completes - complex images fail with "megabyte limit exceeded" and even simple images fail with "tobytes" errors.

**Comment by lyonsjr** [comment]
So, this extensions doesn't work for 64 bit windows? I tried it but received same error as above. Is there any fixes? Does the author support his extension? Thanks for the help!

Traceback (most recent call last):
  File "centerline-trace.py", line 392, in <module>
    e.affect()
  File "D:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "centerline-trace.py", line 359, in effect
    path_svg,stroke_width,im_size = self.svg_centerline_trace(filename)
  File "centerline-trace.py", line 154, in svg_centerline_trace
    im = im.convert(mode='L', dither=None)
  File "D:\Program Files\Inkscape\python\lib\site-packages\PIL\Image.py", line 653, in convert
    self.load()
  File "D:\Program Files\Inkscape\python\lib\site-packages\PIL\ImageFile.py", line 155, in load
    self.load_prepare()
  File "D:\Program Files\Inkscape\python\lib\site-packages\PIL\PngImagePlugin.py", line 339, in load_prepare
    ImageFile.ImageFile.load_prepare(self)
  File "D:\Program Files\Inkscape\python\lib\site-packages\PIL\ImageFile.py", line 223, in load_prepare
    self.im = Image.core.new(self.mode, self.size)
  File "D:\Program Files\Inkscape\python\lib\site-packages\PIL\Image.py", line 36, in __getattr__
    raise ImportError("The _imaging C module is not installed")
ImportError: The _imaging C module is not installed

**Comment by Moini** [comment]
It's not a problem of the extension, it's because Inkscape for Windows comes with its own python bundled, so users don't need to install Python themselves to be able to export things, visit the Inkscape website or to use extensions. 

It appears that the Python that comes with Inkscape doesn't include that module, though, so this extension doesn't work on Windows, unless someone finds out how to replace the Python files (the Xia installer seems to know how to do it, so that might be an option) that have been put on your disk when installing Inkscape.

**Comment by jnweiger** [comment]
Windows supportt from my side is very limited. This extensionwas developped and is maintained for Linux The xia imaging issue never happened to me on Linux.

For there are so many Windows users out there, I hope for someone whocan guide us towards better support for Windows here.

**Comment by arpruss** [comment]
Get get-pip.py (https://pip.pypa.io/en/stable/installing/) and put it in your Inkscape directory (e.g., c:\Program Files (x86)\Inkscape). Start an admin command shell. Go to your Inkscape directory. Then do:
  python\python.exe get-pip.py --trusted-host pypi.python.org
  python\Scripts\pip.exe --trusted-host pypi.python.org install pillow

Drop autotrace.exe in your Inkscape extensions directory (I used the x64 build, which worked even though my Inkscape is x32: https://github.com/scottvr/autotrace-win64-binaries ). Drop the inx and py files from the centerline-trace package in your Inkscape extensions directory.

And then it just works.

**Comment by Moini** [comment]
@arpruss : Cool :) Could you upload this as a tutorial to inkscape.org? I think this might be beneficial for more than just the users affected by this issue here.

**Comment by arpruss** [comment]
How does one upload tutorials?

**Comment by Moini** [comment]
Glad you asked :) 
Create a file (pdf, text, svg, whatever you think fits best), login to inkscape.org (or create an account), use the 'image' icon in the top right corner to find where to upload a new file, enter everything into the form, choose 'Tutorial' for category, Save - Done :)

**Comment by arpruss** [comment]
I'm getting server errors when I try to do that.

**Comment by Moini** [comment]
Oh, I'm sorry @arpruss :-( 
Would you help the website team to fix this by continuing the website issue related conversation at https://bugs.launchpad.net/inkscape-web? Probably one of the latest updates broke file upload...

**Comment by jnweiger** [comment]
@arpruss All thumbs up! Windows support on the horizon. Yeah!

**Comment by arpruss** [comment]
Tutorial posted: https://inkscape.org/en/~arpruss/%E2%98%85centerline-trace-on-windows-instructions

**Comment by justinds89** [comment]
Tried running through the steps, but still unable to get it to work on Windows 10 x64. Any recommendations?

**Comment by arpruss** [comment]
Which step failed?

**Comment by justinds89** [comment]
Appreciate the quick reply. Really would like to get this to work.

I'm getting the error on step 1.6

python\Scripts\pip --trusted-host pypi.python.org install pillow
Fatal error in launcher: Unable to create process using '"'

**Comment by arpruss** [comment]
Are you using an admin-privileged cmd prompt?

**Comment by justinds89** [comment]
Yes I am.

I have also noticed that on step 3.1 that the link no longer works, but I haven't made it that far anyhow.

**Comment by arpruss** [comment]
1. What do you get if you do:
python\Scripts\pip --version

2. Are you using 32-bit or 64-bit Inkscape? I think it should work with both, but I may have only tested with 32-bit.

**Comment by justinds89** [comment]
D:\Program Files\Inkscape>python\scripts\pip --version
Fatal error in launcher: Unable to create process using '"'

Is what I get.

I am using 64-bit Inkscape.

**Comment by arpruss** [comment]
And the get-pip stage gave you no errors?

**Comment by justinds89** [comment]
This is what I get on the get-pip stage.

D:\Program Files\Inkscape>python\python get-pip.py --trusted-host pypi.python.org
Requirement already up-to-date: pip in d:\program files\inkscape\python\lib\site-packages

**Comment by arpruss** [comment]
Does adding --ignore-installed to the get-pip command line help?

**Comment by justinds89** [comment]
That worked! Thanks.

Now I'm stuck at 2.1. That link is no longer valid. Do you have a copy of the file or know where I can get it?

**Comment by justinds89** [comment]
Got it all to work. Thanks so much for the help. Doesn't quite work as I had hoped.

**Comment by arpruss** [comment]
The URL is just fine. Just don't click on the automatic link.

**Comment by justinds89** [comment]
I did get it setup properly. Thanks again for the help!

**Comment by sehjak** [comment]
I followed the Tutorial (nicely done) but CL trace not working: [Error cannot import PIL. Try apt-get install python-pil] So I need something as detailed as the Tutorial re what to do next--I don't know programming. I did see similar fatal error in launcher [unable to create process using '"' ] as in the Command Prompt (Admin) when I tried to reinstall Pillow per Tutorial Instructions #1. Justinds89 refers to it.
Thanks for help and advice.

**Comment by arpruss** [comment]
Did the get-pip line work for you? Did you add --ignore-installed ?

**Comment by sehjak** [comment]
I don't know how or where to do that --

**Comment by arpruss** [comment]
In one of the steps you ran this command:
 python\python get-pip.py --trusted-host pypi.python.org

Try it again but add at the end  --ignore-installed (with a space before it). Then redo all the steps after this.

**Comment by sehjak** [comment]
Msg rec'd: Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected. 

Then: Neither file:// nor data:image/png; prefix. Cannot parse PNG image href data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD//gAyUHJvY2Vzc2VkIEJ5IGVCYXkgd2l0aCBJbWFnZU1hZ2lj aywgejEuMS4wLiB8fEIy/9sAQwAGBAUGBQQGBgUGBwcGCAoQCgoJCQoUDg8MEBcUGBgXFBYWGh0l HxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko/9sAQwEHBwcKCAoTCgoTKBoWGigoKCgoKCgoKCgo KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo/8AAEQgA4QDhAwEiAAIRAQMR Af/ ...and lots more.

So, I started over again Now after enter **python\python get-pip.py --trusted-host pypi.python.org --ignore-installed** I get **The system cannot find the path specified**

**Comment by arpruss** [comment]
Are you in the correct directory?

**Comment by sehjak** [comment]
I thought I did...nothing seems to be working so I am engaging a system restore point before all this started, doing a clean uninstall / reinstall of Inkscape 92 64 bit - btw I am working on an ASUS laptop with Windows10. I will attempt to follow the tutorial from scratch,...again.... and see what happens. I have dwnlded both 64 & 32 bit auto trace- shall I install both or just the 64??

FYI Inkscape is misspelled as Inkspace in several places in the Tutorial & centerline trace link does not work but this one does: **https://github.com/fablabnbg/inkscape-centerline-trace.**

I'll post what happens next. And, finally, the copy/paste function of bitmaps into Inkscape is not working -before and still after the restart...any suggestions? Thx again for your help and suggestions.

**Comment by sehjak** [comment]
OK - starting with a cleaner slate did the trick - CL tracing is working! Thanks so much.

Ideas re copy/paste problems??

**Comment by Moini** [comment]
@arpruss : We found that we still need to add the autotrace.exe's path to the windows path variable: https://github.com/fablabnbg/inkscape-centerline-trace/issues/15 (I copied it into a separate directory).

Would you update your tutorial?

**Comment by KirstenRK** [comment]
So, hi, I am new here. At least, I have re-read everything and now made the plugin work.
I use Windows 8.1, 64 bits, Inkscape 0.91 32 bits.

In the install process, several things went wrong. I got the _C-module error_ and _pillow was incorrectly installed_. Then there was _no autotrace installed_.

But: everything is easier in the end.
This is what I did:
- I installed (the correct) autotrace.exe and the .inx and .py files in the Inkscape _user's_ directory.
- In order to install pillow, in the administrator shell, I added a number behind the line:
python\Scripts\pip --trusted-host pypi.python.org install pillow**==2.7** 

There was no need to add anything to the windows path variable.
So I chanched the instruction file from Alexander Pruss and I add them here as a pdf. Please let us all know if this works for you.
[centerline_NIH0Rhk_changed.pdf](https://github.com/fablabnbg/inkscape-centerline-trace/files/1822909/centerline_NIH0Rhk_changed.pdf)

**Comment by jnweiger** [comment]
@KirstenRK thanks for the report!
Where did you download 'the correct' autotrace.exe ?? I almost gave up on supporting this for windows...

**Comment by KirstenRK** [comment]
Hi jnweiger,
Thank you.
I can now confirm that these instructions work for Inkscape 0.91 under both Windows 8.1 and Windows 10. That's why I have changed the name of my uploaded instructions.

Sadly, it does not work for Inkscape 0.92.2.

**Comment by KirstenRK** [comment]
Installing is very easy with Inkscape 0.92.2 64 bits under Windows.
Just copy the 4 files into the user's extension directory. That is in my case
C:\Users\Kirsten\AppData\Roaming\inkscape\extensions

autotrace.exe https://github.com/scottvr/autotrace-win64-binaries/raw/master/bin/autotrace.exe
centerline-trace.inx,
centerline-trace.py, 
rof.py   https://github.com/fablabnbg/inkscape-centerline-trace


@jnweiger :There is no need for installing Pip and pillow: they were bundled in this build.

**Comment by jnweiger** [comment]
The latest 64bit inkscape 0.92.3 for Windows10 already brings its own PIL, as @KirstenRK found.
Manal copying of files is no longer needed, we now have setup.exe packages for both autotrace and inkscape-centerline-trace

The Installation instructions are now as short as

* install the latest setup.exe from https://github.com/jnweiger/autotrace/releases
* install the latest setup.exe from https://github.com/fablabnbg/inkscape-centerline-trace/releases
* restart inkscape, be happy.

FYI @arpruss your tutorial is sill valid for older packages and older systems, but maybe you can add a note for win10 with inkscape 0.92.2 and up. Thanks!

FYI @sehjak you had tried a jpeg image probably before jpeg support was added. This should now work too.

Closing here. Thank you all for digging into that morass.

**Comment by sehjak** [comment]
Thanks! Much appreciated.
