### ISSUE TITLE
How do I Install this on Mac?

### ISSUE THREAD

**Issue by mikethedj4** [fablabnbg/inkscape-centerline-trace#6]
How do I Install this on Mac?

**Comment by faheus** [comment]
Just do it!
Am 30.09.2016 11:53 nachm. schrieb Michael <notifications@github.com>:How do I Install this on Mac?

**Comment by technorainbows** [comment]
What...? I copied it into the folder that Inkscape says --
"/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions"
and nothing shows up in Inkscape when I relaunch.

Are there any dependencies that should be installed?

Ashley
--
Ashley Newton
www.ashleynewton.net
www.sustainablemagic.org
603.513.2066

<http://sustainablemagic.org/>

**Comment by jnweiger** [comment]
As soon as centerline-trace.py and centerline-trace.inx are in the right location, it should show up
under Extensions -> Images -> Centerline Trace.

Probably @faheus could tell best where that location is. I don't have a mac, sorry.

And yes, it probably does not work out of the box, we also need a number of dependencies:

For debian I can tell the names of the dependency packages: autotrace and python3-pil or python-pil.
Probably named similar on a mac...

**Comment by Moini** [comment]
There's a log file written when Inkscape doesn't find something it needs before launching an extension. It lives next to your personal user preferences.xml file, and should give you a hint as to what is missing for centerline trace.

**Comment by alexkaessner** [comment]
@michaelsboost @Moini It's still not really clear how to install this on macOS. I've downloaded the repository and placed `centerline-trace.py` + `centerline-trace.inx` at the `/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions` location. It also shows up in the extensions menu. But when I try to run the extension an error appears with the following message:

> You need to install autotrace for this extension to work! (Windows/OS X: see https://sourceforge.net/projects/autotrace/, Debian/Ubuntu: apt-get install autotrace.)

But I can't find a way to install _autotrace_ on macOS. Also the link you provide to: http://macappstore.org/autotrace/ isn't working. I get the error `Error: No available formula with the name "autotrace" ` when trying to run `brew install autotrace`.

**Comment by jnweiger** [comment]
@alexkaessner sorry for the installation issues. It seems the autotrace binaries were erased almost everywhere after some obscure security issues surfaced. 

There are several efforts going on, to bring it back. I have succeeded in compiling an autotrace binary for mac on travis, but it is unclear to me, how to extract the binary from there. 

Please check out https://github.com/autotrace/autotrace/issues/4

I am closing here as a duplicate.

**Comment by Moini** [comment]
Additional:
Please do not install the extension files into /Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions - unless that is the folder that is indicated at Edit > Preferences > System: User extensions. Any extensions you install into the folder where you put them will be lost if you uninstall Inkscape or update to a newer version. The others that live in your personal Inkscape extras folder will survive :)

**Comment by Claire2703** [comment]
How do I install the centerline trace option on Mac OS 10.13 High Sierra.

I'm not a computer programmer and just need a step by step guide.
I'm pulling my hair out as nothing I have found online works!
I love Inkscape but the trace bitmap is very clunky - I need centreline trace!

**Comment by Moini** [comment]
Have you seen the instructions for Mac at https://github.com/fablabnbg/inkscape-centerline-trace ?

**Comment by Claire2703** [comment]
Hi there

Yes, I have but I can’t seem to get it to work - I download the file but it comes up as  ‘Autotrace.app”  and I tried the instructions on the terminal but it tells me the python files aren’t there.
thanks
Claire

**Comment by Moini** [comment]
What do you get when you type 

sudo easy_install install pip 

into the command line? (you need to press Enter, then enter your administrator password)
