### ISSUE TITLE
Only PNG works for embedded image

### ISSUE THREAD

**Issue by gjung57** [fablabnbg/inkscape-centerline-trace#8]
Embedded images of all formats except PNG throw an error:
  Neither file:// nor data:image/png; prefix. Cannot parse PNG image ....

To reproduce just import any image which is not of type PNG (eg. JPEG)
as embedded image. Then do a centerline-trace.

**Comment by jnweiger** [comment]
Let's focus on embedded JPEG. (I fail at enumerating 'all formats' today, but I get your point.)
The plugin throws an error message with a hint:
<pre>
Neither file:// nor data:image/png; prefix. Cannot parse PNG image href data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAAMCAgMCAgMDAwME AwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBD
</pre>

The SVG file has it like this:
<pre>
  &lt;g
     inkscape:label="Ebene 1"
     inkscape:groupmode="layer"
     id="layer1">
    &lt;image
       y="219.28162"
       x="-156.18515"
       id="image4163"
       xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAAMCAgMCAgMDAwME
AwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBD
AQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU
FBQUFBQUFBT/wgARCAGQAoADAREAAhEBAxEB/8QAHQABAAAHAQEAAAAAAAAAAAAAAAEDBAUGBwgC
GGM0m3UW8ITc8wErGYthA5QsYHL8pQyg8SWS+EcyMHMwMcUDjK6QK8KdRcD2QWkJNYnpL/U9I0rA
...
vcmjxdn0Ooz0/PrahAtA+4//2Q==
"
       preserveAspectRatio="none"
       height="500"
       width="800" />
  &lt;/g>
&lt;/svg>

</pre>

**Comment by gjung57** [comment]
I don't think you need to enumerate 'all formats'.
I'm pretty sure even with windows it's enough to just write the temporary file as 'image.dat',
the file-header should do the magic.
So just look for "data:image/" to be sure it's an image,
ignore the format descriptor (jump right after the ';'),
look for the encoding (in this case 'base64'),
convert to binary and finally write the temp file 'image.dat'.

**Comment by jnweiger** [comment]
Please check out https://github.com/fablabnbg/inkscape-centerline-trace/releases/tag/v0.5
